Repository mallangC/ChallengeProject, pull requests merged in 2025-04, with the labels that each got.

#32 account 기능을 member와 연결
  build.gradle
  src/main/java/com/zerobase/challengeproject/account/controller/AccountController.java
  src/main/java/com/zerobase/challengeproject/account/service/AccountService.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtAuthorizationFilter.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtUtil.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberLoginController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberSignupController.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberDto.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberLoginResponse.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberLogoutDto.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/RefreshTokenDto.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/entity/RefreshToken.java
  src/main/java/com/zerobase/challengeproject/member/repository/MemberRepository.java
  src/main/java/com/zerobase/challengeproject/member/repository/RefreshTokenRepository.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberLoginService.java
  src/test/java/com/zerobase/challengeproject/account/service/AccountServiceTest.java
Labels: enhancement

#34 refactor:mingang-logout -> 필터 순서 수정 AuthorizationFilter 수정
  src/main/generated/com/zerobase/challengeproject/account/entity/QAccountDetail.java
  src/main/generated/com/zerobase/challengeproject/account/entity/QBaseEntity.java
  src/main/generated/com/zerobase/challengeproject/account/entity/QRefund.java
  src/main/generated/com/zerobase/challengeproject/challenge/entity/QChallenge.java
  src/main/generated/com/zerobase/challengeproject/challenge/entity/QMemberChallenge.java
  src/main/generated/com/zerobase/challengeproject/member/entity/QMember.java
  src/main/java/com/zerobase/challengeproject/account/controller/AccountController.java
  src/main/java/com/zerobase/challengeproject/config/SecurityConfig.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtAuthorizationFilter.java
Labels: duplicate

#35 회원 정보 조회 기능
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtAuthorizationFilter.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberController.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberProfileDto.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/MemberProfileFrom.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberService.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberLoginServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberSignupServiceTest.java
Labels: enhancement

#40 비밀번호 수정 기능, 회원 탈퇴 기능
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberSignupController.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/ChangePasswordForm.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberService.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberSignupService.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberSignupServiceTest.java
Labels: documentation, enhancement

#45 코테 챌린지, 코테 인증 댓글 기능
  src/main/java/com/zerobase/challengeproject/account/controller/AccountAdminController.java
  src/main/java/com/zerobase/challengeproject/account/controller/AccountController.java
  src/main/java/com/zerobase/challengeproject/account/domain/dto/AccountDetailDto.java
  src/main/java/com/zerobase/challengeproject/account/domain/form/RefundSearchForm.java
  src/main/java/com/zerobase/challengeproject/account/entity/AccountDetail.java
  src/main/java/com/zerobase/challengeproject/account/service/AccountService.java
  src/main/java/com/zerobase/challengeproject/challenge/entity/Challenge.java
  src/main/java/com/zerobase/challengeproject/challenge/repository/ChallengeRepository.java
  src/main/java/com/zerobase/challengeproject/challenge/repository/ChallengeRepositoryCustom.java
  src/main/java/com/zerobase/challengeproject/challenge/repository/ChallengeRepositoryCustomImpl.java
  src/main/java/com/zerobase/challengeproject/challenge/service/ChallengeService.java
  src/main/java/com/zerobase/challengeproject/comment/controller/CoteChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/domain/dto/CoteChallengeDto.java
  src/main/java/com/zerobase/challengeproject/comment/domain/dto/CoteCommentDto.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/CoteChallengeForm.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/CoteChallengeUpdateForm.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/CoteCommentForm.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/CoteCommentUpdateForm.java
  src/main/java/com/zerobase/challengeproject/comment/entity/CoteChallenge.java
  src/main/java/com/zerobase/challengeproject/comment/entity/CoteComment.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteChallengeRepository.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteChallengeRepositoryCustom.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteChallengeRepositoryCustomImpl.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteCommentRepository.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteCommentRepositoryCustom.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteCommentRepositoryCustomImpl.java
  src/main/java/com/zerobase/challengeproject/comment/service/CommentService.java
  src/main/java/com/zerobase/challengeproject/config/SecurityConfig.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/repository/MemberRepositoryCustom.java
  src/main/java/com/zerobase/challengeproject/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/zerobase/challengeproject/type/CategoryType.java
  src/main/java/com/zerobase/challengeproject/type/CommentType.java
  src/test/java/com/zerobase/challengeproject/account/service/AccountServiceTest.java
  src/test/java/com/zerobase/challengeproject/challenge/service/ChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/CommentServiceTest.java
Labels: enhancement

#39 계좌 내역 기능 추가
  src/main/java/com/zerobase/challengeproject/account/domain/dto/AccountDetailDto.java
  src/main/java/com/zerobase/challengeproject/account/domain/form/RefundSearchForm.java
  src/main/java/com/zerobase/challengeproject/account/entity/AccountDetail.java
  src/main/java/com/zerobase/challengeproject/account/service/AccountService.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/zerobase/challengeproject/type/AccountType.java
Labels: enhancement

#63 코테챌린지, 다이어트챌린지 환급기능 추가
  src/main/generated/com/zerobase/challengeproject/account/entity/QAccountDetail.java
  src/main/generated/com/zerobase/challengeproject/account/entity/QBaseEntity.java
  src/main/generated/com/zerobase/challengeproject/account/entity/QRefund.java
  src/main/generated/com/zerobase/challengeproject/challenge/entity/QChallenge.java
  src/main/generated/com/zerobase/challengeproject/challenge/entity/QMemberChallenge.java
  src/main/generated/com/zerobase/challengeproject/comment/entity/QCoteChallenge.java
  src/main/generated/com/zerobase/challengeproject/comment/entity/QCoteComment.java
  src/main/generated/com/zerobase/challengeproject/comment/entity/QDietChallenge.java
  src/main/generated/com/zerobase/challengeproject/comment/entity/QDietComment.java
  src/main/generated/com/zerobase/challengeproject/member/entity/QMember.java
  src/main/generated/com/zerobase/challengeproject/member/entity/QRefreshToken.java
  src/main/java/com/zerobase/challengeproject/ChallengeProjectApplication.java
  src/main/java/com/zerobase/challengeproject/account/entity/AccountDetail.java
  src/main/java/com/zerobase/challengeproject/challenge/controller/ChallengeController.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/dto/DepositBackDto.java
  src/main/java/com/zerobase/challengeproject/challenge/entity/MemberChallenge.java
  src/main/java/com/zerobase/challengeproject/challenge/service/ChallengeService.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/CoteChallengeForm.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/CoteCommentForm.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/DietChallengeAddForm.java
  src/main/java/com/zerobase/challengeproject/comment/domain/form/DietCommentAddForm.java
  src/main/java/com/zerobase/challengeproject/comment/entity/CoteChallenge.java
  src/main/java/com/zerobase/challengeproject/comment/entity/CoteComment.java
  src/main/java/com/zerobase/challengeproject/comment/entity/DietChallenge.java
  src/main/java/com/zerobase/challengeproject/comment/entity/DietComment.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteChallengeRepository.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteChallengeRepositoryCustomImpl.java
  src/main/java/com/zerobase/challengeproject/comment/repository/CoteCommentRepository.java
  src/main/java/com/zerobase/challengeproject/comment/repository/DietChallengeRepository.java
  src/main/java/com/zerobase/challengeproject/comment/repository/DietCommentRepository.java
  src/main/java/com/zerobase/challengeproject/comment/service/CoteChallengeService.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/ChangePasswordForm.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/MemberLoginForm.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/MemberProfileFrom.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/MemberSignupForm.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/test/java/com/zerobase/challengeproject/challenge/service/ChallengeServiceTest.java
Labels: enhancement

#72 소셜 로그인 테스트
  build.gradle
  src/test/java/com/zerobase/challengeproject/member/oauth/OAuthAuthenticationTest.java
Labels: enhancement

#78 관리자 블랙리스트 등록 기능 추가
  src/main/java/com/zerobase/challengeproject/config/SecurityConfig.java
  src/main/java/com/zerobase/challengeproject/exception/BlacklistedMemberException.java
  src/main/java/com/zerobase/challengeproject/exception/CustomException.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/exception/GlobalExceptionHandler.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/CustomAuthenticationProvider.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/UserDetailsServiceImpl.java
  src/main/java/com/zerobase/challengeproject/member/components/oauthHandler/OAuth2FailureHandler.java
  src/main/java/com/zerobase/challengeproject/member/contoller/AdminBlackListController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberLoginController.java
  src/main/java/com/zerobase/challengeproject/member/domain/form/BlackListRegisterForm.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/repository/RefreshTokenRepository.java
  src/main/java/com/zerobase/challengeproject/member/service/AdminBlacklistService.java
  src/main/java/com/zerobase/challengeproject/member/service/CustomOAuth2UserService.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberLoginService.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberSignupService.java
  src/test/java/com/zerobase/challengeproject/comment/service/WaterChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/LoginIntegrationTest.java
  src/test/java/com/zerobase/challengeproject/member/components/jwt/UserDetailsServiceImplTest.java
  src/test/java/com/zerobase/challengeproject/member/service/AdminBlacklistServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberLoginServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberSignupServiceTest.java
Labels: documentation, enhancement

#82 블랙리스 해제 기능 추가 및 멘토님 리뷰 후 코드 수정
  build.gradle
  src/main/java/com/zerobase/challengeproject/HttpApiPageResponse.java
  src/main/java/com/zerobase/challengeproject/account/controller/AccountAdminController.java
  src/main/java/com/zerobase/challengeproject/account/controller/AccountController.java
  src/main/java/com/zerobase/challengeproject/account/service/AccountService.java
  src/main/java/com/zerobase/challengeproject/comment/controller/AdminChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/controller/CoteChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/controller/DietChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/service/CoteChallengeService.java
  src/main/java/com/zerobase/challengeproject/comment/service/DietChallengeService.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/components/jwt/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/challengeproject/member/contoller/AdminBlackListController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberLoginController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberSignupController.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberDto.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberEmailAuthDto.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberProfileDto.java
  src/main/java/com/zerobase/challengeproject/member/domain/dto/MemberSignupDto.java
  src/main/java/com/zerobase/challengeproject/member/entity/Member.java
  src/main/java/com/zerobase/challengeproject/member/service/AdminBlacklistService.java
  src/main/java/com/zerobase/challengeproject/member/service/CustomOAuth2UserService.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberLoginService.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberService.java
  src/main/java/com/zerobase/challengeproject/member/service/MemberSignupService.java
  src/test/java/com/zerobase/challengeproject/account/service/AccountServiceTest.java
  src/test/java/com/zerobase/challengeproject/challenge/service/ChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/CoteChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/DietChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/LoginIntegrationTest.java
  src/test/java/com/zerobase/challengeproject/member/components/jwt/CustomAuthenticationProviderTest.java
  src/test/java/com/zerobase/challengeproject/member/components/jwt/UserDetailsServiceImplTest.java
  src/test/java/com/zerobase/challengeproject/member/oauth/OAuthAuthenticationTest.java
  src/test/java/com/zerobase/challengeproject/member/service/AdminBlacklistServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberLoginServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberSignupServiceTest.java
Labels: documentation, enhancement

#84 코드리뷰 리팩토링
  src/main/java/com/zerobase/challengeproject/HttpApiResponse.java
  src/main/java/com/zerobase/challengeproject/PagenatedResponseDto.java
  src/main/java/com/zerobase/challengeproject/account/controller/AccountAdminController.java
  src/main/java/com/zerobase/challengeproject/account/controller/AccountController.java
  src/main/java/com/zerobase/challengeproject/account/service/AccountService.java
  src/main/java/com/zerobase/challengeproject/challenge/controller/AdminController.java
  src/main/java/com/zerobase/challengeproject/challenge/controller/ChallengeController.java
  src/main/java/com/zerobase/challengeproject/challenge/controller/SearchController.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/dto/DepositBackDto.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/dto/GetChallengeDto.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/dto/HttpApiResponse.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/dto/ParticipationChallengeDto.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/dto/RegistrationChallengeDto.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/request/CreateChallengeRequest.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/request/RegistrationChallengeRequest.java
  src/main/java/com/zerobase/challengeproject/challenge/domain/request/UpdateChallengeRequest.java
  src/main/java/com/zerobase/challengeproject/challenge/entity/Challenge.java
  src/main/java/com/zerobase/challengeproject/challenge/entity/MemberChallenge.java
  src/main/java/com/zerobase/challengeproject/challenge/repository/ChallengeRepository.java
  src/main/java/com/zerobase/challengeproject/challenge/service/AdminChallengeService.java
  src/main/java/com/zerobase/challengeproject/challenge/service/ChallengeService.java
  src/main/java/com/zerobase/challengeproject/challenge/service/SearchService.java
  src/main/java/com/zerobase/challengeproject/comment/controller/AdminChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/controller/CoteChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/controller/DietChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/controller/WaterChallengeController.java
  src/main/java/com/zerobase/challengeproject/comment/service/CoteChallengeService.java
  src/main/java/com/zerobase/challengeproject/comment/service/DietChallengeService.java
  src/main/java/com/zerobase/challengeproject/comment/service/WaterChallengeService.java
  src/main/java/com/zerobase/challengeproject/exception/ErrorCode.java
  src/main/java/com/zerobase/challengeproject/member/contoller/AdminBlackListController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberLoginController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberSignupController.java
  src/test/java/com/zerobase/challengeproject/account/service/AccountServiceTest.java
  src/test/java/com/zerobase/challengeproject/challenge/service/ChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/CoteChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/DietChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/WaterChallengeServiceTest.java
Labels: enhancement

#85 충돌 수정
  src/main/java/com/zerobase/challengeproject/account/service/AccountService.java
  src/main/java/com/zerobase/challengeproject/challenge/service/ChallengeService.java
  src/main/java/com/zerobase/challengeproject/comment/service/WaterChallengeService.java
  src/main/java/com/zerobase/challengeproject/member/contoller/AdminBlackListController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberLoginController.java
  src/main/java/com/zerobase/challengeproject/member/contoller/MemberSignupController.java
  src/test/java/com/zerobase/challengeproject/challenge/service/ChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/LoginIntegrationTest.java
  src/test/java/com/zerobase/challengeproject/member/service/MemberSignupServiceTest.java
Labels: bug

#87 ignore 수정
  .gitignore
  gradle/wrapper/gradle-wrapper.properties
  src/test/java/com/zerobase/challengeproject/ChallengeProjectApplicationTests.java
  src/test/java/com/zerobase/challengeproject/challenge/service/ChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/CoteChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/comment/service/WaterChallengeServiceTest.java
  src/test/java/com/zerobase/challengeproject/member/LoginIntegrationTest.java
  src/test/java/com/zerobase/challengeproject/member/oauth/OAuthAuthenticationTest.java
Labels: bug

#88 flyway 추가
  build.gradle
  src/main/resources/application.yml
Labels: bug
